services:
  - type: web
    name: 2k-spark-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/api.py
    envVars:
      - key: CORS_ORIGINS
        value: "https://2k-spark.vercel.app"
